# Generated by Django 4.1.1 on 2022-10-05 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='views',
            new_name='views_count',
        ),
    ]
